### ISSUE TITLE
Error emails after payment. Unexpected Exception... Task send_email raised unexpected: ValueError(u'Plugin not active: payment_sixpay', )

### ISSUE THREAD

**Issue by selkieupsilon** [maxfischer2781/indico_sixpay#9]
I received some error messages by email when using the plugin and the test account.

I followed the installation instructions. I enabled the plugin in etc/indico.conf (PLUGINS = {'payment_manual', 'payment_paypal', 'payment_sixpay'}), then entered the test system URL and also the test ID. I enabled the plugin for the Indico event that I want to use for testing.

Generally, the payment proceeds fine on the test system. As a test user, I start with the Indico bill page, get transferred to the safepay page, then return to the Indico bill which shows that the bill is successfully paid. I also successfully receive emails as the vendor (titled: Test: Einkauf über Saferpay) and also as the test user (title: Test: Thank you for your payment). But in between those two emails, as the Indico system administrator, I receive two error messages.

Subject of the email: Unexpected Exception occurred at <SERVER>: Task send_email[1a4b267f-58de-492c-8adc-f68816a468c0] raised unexpected: ValueError(u'Plugin not active: payment_sixpay', )
Text of the email:
2018-12-06 18:43:48,251  0000000000000000  celery.app.trace - ERROR trace.py:249 -- Task send_email[1a4b267f-58de-492c-8adc-f68816a468c0] raised unexpected: ValueError(u'Plugin not active: payment_sixpay',)

Traceback (most recent call last):
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/core/celery/core.py", line 150, in __call__
    raise ValueError('Plugin not active: ' + plugin_name)
ValueError: Plugin not active: payment_sixpay

Here are our Indico installation details:
    Server default language (en_GB)
    Indico version installed (2.1.4)
    Python version used (2.7.15rc1)
    Postgres version used (9.6.11)
    Operating system used (Linux Ubuntu 18.04)
    Debug mode (disabled)

I am not sure why these errors occurred since the plugin is obviously enabled and the email was sent successfully. Any help to get rid of this annoying error would be appreciated.

**Comment by maxfischer2781** [comment]
This might be related to how `indico` loads its plugins. Have you tried restarting the indico service?
```
systemctl restart indico-celery.service
```

**Comment by selkieupsilon** [comment]
Thank you for the speedy reply, that does indeed seem to have resolved the problem. 

I agree that having this step in the installation guide would be helpful.

I have also just updated to Indico 2.1.5 and it works fine.

**Comment by maxfischer2781** [comment]
Thanks a lot for the report. I have expanded the docs with restarting the services in bbb3d4f4cadf89bf5218eabf6bdeff1edcbf28e7.
